language: minimal
dist: bionic

git:
  quiet: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
      key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    update: true
    packages:
    - buildah

script:
- echo $quayiopassword | buildah login -u $quayiouser --password-stdin quay.io
- echo $githubtoken | buildah login -u $quayiouser --password-stdin ghcr.io
- sudo ./run.sh

after_success:
- sudo buildah push oraclelinux-haskell-builder:latest docker://quay.io/$quayiouser/oraclelinux-haskell-builder:latest
- sudo buildah push oraclelinux-haskell-builder:latest docker://ghcr.io/$quayiouser/oraclelinux-haskell-builder:latest

after_script:
- buildah logout quay.io
- buildah logout ghcr.io
